### ISSUE TITLE
Issue Running "REHdynamics/data-raw/1_data_generation.R" - Error with 'remify' Package

### ISSUE THREAD

**Issue by Mbehbahani** [mlmeijerink/REHdynamics#1]
Hi there,

I hope you are doing well. I'm encountering an issue when attempting to run the "REHdynamics/data-raw/1_data_generation.R" script. Specifically, I'm facing the following error:

Error: 'reh' is not an exported object from 'namespace:remify'

This error occurs when I reach the following line of code:

```R
constant[[r]] <- generate(formula, param$constant, M = 10000, covar)
```

Could you please guide me in resolving this issue? I appreciate your help.

**Comment by mlmeijerink** [comment]
Based on the error it seems like you downloaded a newer version of remify that is not compatible with this repository. I recommend you to go back to the older version, using the installation instructions in the readme.md file.
